#!/bin/bash -e

echocol() { echo -e "\033[31m$@...\033[0m " >&2; }

echocol "Setup dirs"

tempdir=$(mktemp -d /tmp/tm-XXXXXXXXX) || exit 1

mkdir -p $tempdir/dist
mkdir -p ./vendor

echocol "Vendorizing [begin]"
if [ ! -d ./vendor/bs4 ]; then
	echocol "Getting Requests"
	curl -sL https://www.crummy.com/software/BeautifulSoup/bs4/download/4.5/beautifulsoup4-4.5.0.tar.gz | tar -C ./vendor --strip 1 --wildcards -zxvf - '*/bs4'
fi
if [ ! -d ./vendor/requests ]; then
	echocol "Getting Beautiful Soup"
	curl -sL https://github.com/kennethreitz/requests/archive/v2.12.3.tar.gz | tar -C ./vendor --strip 1 --wildcards -zxvf - '*/requests'
fi
echocol "Vendorizing [end]"

echocol "Copying source files to dist"

cp -rv ./soglie-tre/__main__.py $tempdir/dist
cp -rv ./vendor/* $tempdir/dist

echocol "Compiling and removing source files"

( cd $tempdir/dist; python -m compileall . )
find $tempdir/dist -name client -prune -o -name \*.py -exec rm {} \;

echocol "Preparing zip file"

( cd $tempdir/dist; zip -9r $tempdir/soglie_tre.zip . )
echo '#!/usr/bin/env python' > $(pwd)/soglie_tre
cat $tempdir/soglie_tre.zip >> $(pwd)/soglie_tre
chmod u+rx $(pwd)/soglie_tre

rm -rf $tempdir
